In [4]:
import torch
from torch import nn
import torch.nn.functional as F

In [5]:
def recon_loss( x, x_hat):
    """
    ADD DOCSTRING!!!
    """
    batch_size = x.shape[0]
    loss =F.mse_loss(x, x_hat, reduction='none')
    loss = loss.view(batch_size, -1).sum(axis=1)
    loss = loss.mean()
    return loss

In [6]:
def recon_loss2( x, x_hat):
    """
    ADD DOCSTRING!!!
    """
    batch_size = x.shape[0]
    loss = nn.MSELoss(reduction='none')(x, x_hat)
    loss = loss.view(batch_size, -1).sum(axis=1)
    loss = loss.mean()
    return loss

In [7]:
x = torch.ones((4,5), requires_grad=True)
print(x)

x_hat = torch.rand_like(x)
print(x_hat)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
tensor([[0.2456, 0.6061, 0.6894, 0.3184, 0.2796],
        [0.1244, 0.2897, 0.3857, 0.9241, 0.6988],
        [0.7230, 0.8719, 0.5641, 0.9822, 0.1038],
        [0.7798, 0.0593, 0.2094, 0.4049, 0.1569]])


In [8]:
loss1 = recon_loss(x, x_hat)
loss2 = recon_loss2(x, x_hat)

print(f"loss1: {loss1} loss2: {loss2}")

loss1: 1.814831256866455 loss2: 1.814831256866455


In [9]:
loss1

tensor(1.8148, grad_fn=<MeanBackward0>)

In [10]:
loss2

tensor(1.8148, grad_fn=<MeanBackward0>)

In [11]:
class MSE:
    """
    ADD DOCSTRING!!!
    """
    def __call__(self, x, x_hat):
        batch_size = x.shape[0]
        loss = nn.MSELoss(reduction='none')(x, x_hat)
        loss = loss.view(batch_size, -1).sum(axis=1)
        loss = loss.mean()
        return loss

In [12]:
MSE()(x, x_hat)

tensor(1.8148, grad_fn=<MeanBackward0>)

In [19]:
import numpy as np
q = np.array([[0.2267, 0.1953, 0.1735, 0.0688, 0.3356],
        [0.2074, 0.2786, 0.1193, 0.2394, 0.1553],
        [0.1337, 0.1074, 0.2844, 0.1082, 0.3664]])
l = np.array([[ 7.9840,  8.3297, 11.4494],
                [6.4572, 5.1127, 6.6388],
                [6.1410, 5.3430, 7.9671],
                [8.1180, 8.3151, 8.7442],
                [8.0247, 7.1036, 8.0665]])

In [20]:
[q[:, i]*l[i] for i in range(5)]

[array([1.8099728 , 1.72757978, 1.53078478]),
 array([1.26109116, 1.42439822, 0.71300712]),
 array([1.0654635 , 0.6374199 , 2.26584324]),
 array([0.5585184 , 1.99063494, 0.94612244]),
 array([2.69308932, 1.10318908, 2.9555656 ])]

In [34]:
l * q.T

array([[1.8099728 , 1.72757978, 1.53078478],
       [1.26109116, 1.42439822, 0.71300712],
       [1.0654635 , 0.6374199 , 2.26584324],
       [0.5585184 , 1.99063494, 0.94612244],
       [2.69308932, 1.10318908, 2.9555656 ]])

In [21]:
np.sum([q[:, i]*l[i] for i in range(5)], axis=0)

array([7.38813518, 6.88322192, 8.41132318])

In [22]:
np.sum([q[:, i]*l[i] for i in range(5)], axis=0) + np.array([-1.5100, -1.5674, -1.4747])

array([5.87813518, 5.31582192, 6.93662318])

In [23]:
8.41132318 - 1.4747

6.93662318

In [33]:
l * q.T

array([[1.8099728 , 1.72757978, 1.53078478],
       [1.26109116, 1.42439822, 0.71300712],
       [1.0654635 , 0.6374199 , 2.26584324],
       [0.5585184 , 1.99063494, 0.94612244],
       [2.69308932, 1.10318908, 2.9555656 ]])

In [8]:
import torch
batch_size = 4
k = 5

# Example tensor
qy = torch.tensor([[5, 4, 2, 3, 1], [5, 4, 3, 2, 1], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
y_hat = torch.argmax(qy, dim=-1)  # Indices obtained from y_hat
print(y_hat)

# Create tensor with 1s at specified indices
y_ = torch.zeros(batch_size, k)
y_ = torch.scatter(y_, 1, y_hat.unsqueeze(1), 1)

print(y_)

tensor([0, 0, 4, 4])
tensor([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]])


In [12]:
import torch
batch_size = 64
k = 10
y_ = torch.zeros([batch_size, k])
print(f"y_ shape: {y_.shape}")
for i in range(k):
    y = y_ + torch.eye(k)[i]
print(f"y: {y} shape: {y.shape}")

y_ shape: torch.Size([64, 10])
y: tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0.,

In [ ]:
import torch
batch_size = 3
k = 5
y_ = torch.zeros([batch_size, k])
print(f"y_ shape: {y_.shape}")
for i in range(k):
    y = y_ + torch.eye(k)[i]
    print(f"y: {y} shape: {y.shape}")

In [1]:
import torch

In [4]:
x = torch.randn(3,5)
xx = torch.nn.Softmax(dim=1)(x)
print(xx)
print(torch.sum(xx, dim=1))

tensor([[0.2145, 0.2130, 0.3700, 0.0691, 0.1334],
        [0.0408, 0.2898, 0.0586, 0.4237, 0.1871],
        [0.1669, 0.2629, 0.2627, 0.1270, 0.1805]])
tensor([1.0000, 1.0000, 1.0000])


In [7]:
x.device

device(type='cpu')

In [3]:
import torch
d = "cpu"
torch.device("cuda" if (torch.cuda.is_available() and d == "cuda") else "cpu")

device(type='cpu')

In [5]:
import numpy as np

l = []
x = np.array([1, 2, 3])
l.extend(x)
print(l)

[1, 2, 3]


In [6]:
def get_accuracy(self, y_true, y_pred):
    n_classes = self.k
    corrected_pred = np.zeros_like(y_pred)
    for cls in range(n_classes):
        indx = y_pred == cls
        true_cls = np.argmax(np.unique(y_true[indx], return_counts=True))
        corrected_pred[indx] = true_cls
    acc = np.mean(y_true == corrected_pred)
    return acc

In [7]:
def get_accuracy(self, y_true, y_pred):
    n_classes = self.k
    corrected_pred = np.zeros_like(y_pred)
    for cls in range(n_classes):
        indx = y_pred == cls
        true_cls = np.argmax(np.unique(y_true[indx], return_counts=True))
        corrected_pred[indx] = true_cls
    acc = np.mean(y_true == corrected_pred)
    return acc

In [29]:
def get_accuracy(y_true, y_pred, k):
    n_classes = k
    corrected_pred = np.zeros_like(y_pred)
    for cls in range(n_classes):
        indx = y_pred == cls
        true_cls = np.bincount(y_true[indx]).argmax()
        corrected_pred[indx] = true_cls
    acc = np.mean(y_true == corrected_pred)
    return acc

In [31]:
y_true = np.array([0, 0, 0, 1, 1, 1, 2, 2])
y_pred = np.array([2, 2, 0, 0, 0, 0, 1, 1])

get_accuracy(y_true, y_pred, 3)

true class: 1
cls: 0 corrected: [0 0 1 1 1 1 0 0]
true class: 2
cls: 1 corrected: [0 0 1 1 1 1 2 2]
true class: 0
cls: 2 corrected: [0 0 1 1 1 1 2 2]
[0 0 0 1 1 1 2 2]
[0 0 1 1 1 1 2 2]


0.875

In [64]:
from collections import defaultdict

d = defaultdict(dict)
ids = [1, 2]
out_infer = {"a": np.array([[1, 1],[2, 2]]), "b": np.array([[10, 10],[20, 20]])}
for ind, id in enumerate(ids):
    for key in out_infer.keys():
        d[id].setdefault(key, []).append(out_infer[key][ind])
print(d)

defaultdict(<class 'dict'>, {1: {'a': [array([1, 1])], 'b': [array([10, 10])]}, 2: {'a': [array([2, 2])], 'b': [array([20, 20])]}})


In [38]:
from torchvision import datasets, transforms 

transform = transforms.ToTensor()
train_dataset = datasets.MNIST(root='data', train=True, transform=transform, download=True)
test_dataset = datasets.MNIST(root='data', train=False, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=2048, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=2048, shuffle=False)

In [41]:
print(test_dataset.data.shape)
print(test_dataset.classes)
print(test_dataset.targets)

torch.Size([10000, 28, 28])
['0 - zero', '1 - one', '2 - two', '3 - three', '4 - four', '5 - five', '6 - six', '7 - seven', '8 - eight', '9 - nine']
tensor([7, 2, 1,  ..., 4, 5, 6])


In [49]:
# Example tensor
tensor = torch.tensor([7, 2, 1, 4, 5, 6, 7, 2, 1, 3, 4, 2, 7])

# Get unique values and their respective counts
unique_values = tensor.unique(return_counts=False)

# Initialize a list to store the random indices
random_indices = []

# Iterate over unique values
for value in unique_values:
    # Get indices of the current value
    indices = torch.where(tensor == value)[0]
    print(f" value: {value} indices: {indices}")

    # Get a random index from the indices
    random_index = torch.randperm(len(indices))[:2]
    
    # Add the random index to the list
    random_indices.extend(indices[random_index])

# Convert the list to a tensor
random_indices_tensor = torch.tensor(random_indices)

# Print the random indices
print(random_indices_tensor)

 value: 1 indices: tensor([2, 8])
 value: 2 indices: tensor([ 1,  7, 11])
 value: 3 indices: tensor([9])
 value: 4 indices: tensor([ 3, 10])
 value: 5 indices: tensor([4])
 value: 6 indices: tensor([5])
 value: 7 indices: tensor([ 0,  6, 12])
tensor([ 2,  8, 11,  1,  9,  3, 10,  4,  5,  0,  6])


In [45]:
tensor[:100]

tensor([7, 2, 1, 4, 5, 6, 7, 2, 1, 3, 4, 2, 7])

In [50]:
dic = {1: 1}

In [58]:
list(map(str, dic.keys()))

['1']

In [134]:
from matplotlib.animation import FuncAnimation, PillowWriter
import json
import matplotlib.pyplot as plt

with open("ids_history.json", "r") as file:
    data = json.load(file)

num_rows = len(data.keys())
print(num_rows)
num_columns = 3

fig, axs = plt.subplots(nrows=num_rows, ncols=num_columns ,sharex=False,sharey=False, figsize=(8,10), gridspec_kw={'width_ratios': [3, 1, 1]})
def animate_diff(i, data):
    ids = list(data.keys())
    plots = []
    for row in range(num_rows):
        for col in range(num_columns):
            row_id = ids[row]
            axs[row, col].clear()
            axs[row, 0].set_ylim([0,1])
            axs[row, 0].set_xticks(range(0,10))
        plots.append(axs[row, 0].bar(range(10), data[row_id]["qy"][i]))
        plots.append(axs[row, 1].imshow(np.reshape(data[row_id]["x_true"], (28,28))))
        plots.append(axs[row, 2].imshow(np.reshape(data[row_id]["x_hat"][i], (28,28))))
    plt.suptitle(f"Frame {i+1}")    #plots.append(axs[row, col].imshow(data[i,(row*num_columns)+col,0,:,:21],vmin=(data[i,:,0,:,:21]).min(), vmax=(data[i,:,0,:,:21]).max()))
    return plots
#print("x_gen shape:", data.shape)
ani = FuncAnimation(fig, animate_diff, fargs=[data],  interval=200, blit=False, repeat=True, frames=3)
#img_path = save_dir + '/images/'
#os.makedirs(os.path.dirname(img_path), exist_ok=True)
#ani.save(img_path + f"gif_ep{ep}_w{w}.gif", dpi=100, writer=PillowWriter(fps=5))
#print('saved image at ' + save_dir + f"gif_ep{ep}_w{w}.gif")
ani.save(f"gif_ep.gif", dpi=100, writer=PillowWriter(fps=5))
plt.close('all')

10


In [133]:
k = list(data.keys())
d = data[k[0]]["x_true"]
print(type(d), len(d), len(d[0]))
d = data[k[0]]["x_hat"]
print(type(d), len(d), len(d[0]))

<class 'list'> 28 28
<class 'list'> 3 10


In [68]:
import json


data = {
    "id1": {
        'array1': np.array([[1, 2, 3], [4, 5, 6]]),
        'array2': np.array([10, 11, 12])
    },
    "id2": {
        'array1': np.array([[1, 2, 3], [4, 5, 6]]),
        'array2': np.array([7, 8, 9])
    }
}



def history_printer(data, indent=0):
    for key, value in data.items():
        print('\t' * indent + f"{key}: {type(value)}")
        if isinstance(value, dict):
            history_printer(value, indent + 1)

In [71]:
import numpy as np
l = np.array([1, 2, 3])
print(type(l[0]))
l = l.astype(np.int32)
print(type(l[0]))

<class 'numpy.int64'>
<class 'numpy.int32'>
