In [4]:
import torch
from torch import nn
import torch.nn.functional as F

In [5]:
def recon_loss( x, x_hat):
    """
    ADD DOCSTRING!!!
    """
    batch_size = x.shape[0]
    loss =F.mse_loss(x, x_hat, reduction='none')
    loss = loss.view(batch_size, -1).sum(axis=1)
    loss = loss.mean()
    return loss

In [6]:
def recon_loss2( x, x_hat):
    """
    ADD DOCSTRING!!!
    """
    batch_size = x.shape[0]
    loss = nn.MSELoss(reduction='none')(x, x_hat)
    loss = loss.view(batch_size, -1).sum(axis=1)
    loss = loss.mean()
    return loss

In [7]:
x = torch.ones((4,5), requires_grad=True)
print(x)

x_hat = torch.rand_like(x)
print(x_hat)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
tensor([[0.2456, 0.6061, 0.6894, 0.3184, 0.2796],
        [0.1244, 0.2897, 0.3857, 0.9241, 0.6988],
        [0.7230, 0.8719, 0.5641, 0.9822, 0.1038],
        [0.7798, 0.0593, 0.2094, 0.4049, 0.1569]])


In [8]:
loss1 = recon_loss(x, x_hat)
loss2 = recon_loss2(x, x_hat)

print(f"loss1: {loss1} loss2: {loss2}")

loss1: 1.814831256866455 loss2: 1.814831256866455


In [9]:
loss1

tensor(1.8148, grad_fn=<MeanBackward0>)

In [10]:
loss2

tensor(1.8148, grad_fn=<MeanBackward0>)

In [11]:
class MSE:
    """
    ADD DOCSTRING!!!
    """
    def __call__(self, x, x_hat):
        batch_size = x.shape[0]
        loss = nn.MSELoss(reduction='none')(x, x_hat)
        loss = loss.view(batch_size, -1).sum(axis=1)
        loss = loss.mean()
        return loss

In [12]:
MSE()(x, x_hat)

tensor(1.8148, grad_fn=<MeanBackward0>)

In [19]:
import numpy as np
q = np.array([[0.2267, 0.1953, 0.1735, 0.0688, 0.3356],
        [0.2074, 0.2786, 0.1193, 0.2394, 0.1553],
        [0.1337, 0.1074, 0.2844, 0.1082, 0.3664]])
l = np.array([[ 7.9840,  8.3297, 11.4494],
                [6.4572, 5.1127, 6.6388],
                [6.1410, 5.3430, 7.9671],
                [8.1180, 8.3151, 8.7442],
                [8.0247, 7.1036, 8.0665]])

In [20]:
[q[:, i]*l[i] for i in range(5)]

[array([1.8099728 , 1.72757978, 1.53078478]),
 array([1.26109116, 1.42439822, 0.71300712]),
 array([1.0654635 , 0.6374199 , 2.26584324]),
 array([0.5585184 , 1.99063494, 0.94612244]),
 array([2.69308932, 1.10318908, 2.9555656 ])]

In [34]:
l * q.T

array([[1.8099728 , 1.72757978, 1.53078478],
       [1.26109116, 1.42439822, 0.71300712],
       [1.0654635 , 0.6374199 , 2.26584324],
       [0.5585184 , 1.99063494, 0.94612244],
       [2.69308932, 1.10318908, 2.9555656 ]])

In [21]:
np.sum([q[:, i]*l[i] for i in range(5)], axis=0)

array([7.38813518, 6.88322192, 8.41132318])

In [22]:
np.sum([q[:, i]*l[i] for i in range(5)], axis=0) + np.array([-1.5100, -1.5674, -1.4747])

array([5.87813518, 5.31582192, 6.93662318])

In [23]:
8.41132318 - 1.4747

6.93662318

In [33]:
l * q.T

array([[1.8099728 , 1.72757978, 1.53078478],
       [1.26109116, 1.42439822, 0.71300712],
       [1.0654635 , 0.6374199 , 2.26584324],
       [0.5585184 , 1.99063494, 0.94612244],
       [2.69308932, 1.10318908, 2.9555656 ]])

In [8]:
import torch
batch_size = 4
k = 5

# Example tensor
qy = torch.tensor([[5, 4, 2, 3, 1], [5, 4, 3, 2, 1], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
y_hat = torch.argmax(qy, dim=-1)  # Indices obtained from y_hat
print(y_hat)

# Create tensor with 1s at specified indices
y_ = torch.zeros(batch_size, k)
y_ = torch.scatter(y_, 1, y_hat.unsqueeze(1), 1)

print(y_)

tensor([0, 0, 4, 4])
tensor([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]])


In [12]:
import torch
batch_size = 64
k = 10
y_ = torch.zeros([batch_size, k])
print(f"y_ shape: {y_.shape}")
for i in range(k):
    y = y_ + torch.eye(k)[i]
print(f"y: {y} shape: {y.shape}")

y_ shape: torch.Size([64, 10])
y: tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0.,

In [ ]:
import torch
batch_size = 3
k = 5
y_ = torch.zeros([batch_size, k])
print(f"y_ shape: {y_.shape}")
for i in range(k):
    y = y_ + torch.eye(k)[i]
    print(f"y: {y} shape: {y.shape}")

In [1]:
import torch

In [4]:
x = torch.randn(3,5)
xx = torch.nn.Softmax(dim=1)(x)
print(xx)
print(torch.sum(xx, dim=1))

tensor([[0.2145, 0.2130, 0.3700, 0.0691, 0.1334],
        [0.0408, 0.2898, 0.0586, 0.4237, 0.1871],
        [0.1669, 0.2629, 0.2627, 0.1270, 0.1805]])
tensor([1.0000, 1.0000, 1.0000])


In [7]:
x.device

device(type='cpu')